env: "local" # local, dev, prod
storage_path: "./storage/storage.db"
http_server:
  adress: "localhost:8082"
  timeout: 4s # время на чтение и на отправку ответа
  idle_timeout: 60s # время жизни соединения с клиентом
postgres:
  host: 127.0.0.1
  port: "5432"
  username: postgres
  password: 03032006
  dbname: postgres
  sslmode: disable
