env: "local" # local, dev, prod
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s # время на чтение и на отправку ответа
  idle_timeout: 60s # время жизни соединения с клиентом
  user: "sj_shoff"
  password: "03032006"
postgres:
  host: db
  port: "5432"
  username: postgres
  password: 03032006
  dbname: postgres
  sslmode: disable
